### ISSUE TITLE
move baselines to separate repo and add MAML

### ISSUE THREAD

**Issue by Howuhh** [corl-team/xland-minigrid#12]
or reptile as a more simpler variation?

**Comment by alexunderch** [comment]
Hey! Do you seek to adapt any particular maml implementation or just redo one from the paper?

**Comment by Howuhh** [comment]
Hi @alexunderch! Personally, I am totally new to the context-based meta-RL and will definitely do first iteration based on some reference implementation to properly understand how it all works. I am planning to use [clean implementation](https://github.com/EdanToledo/JAX-MAML) from @EdanToledo and some explore some variants described [here](https://interactive-maml.github.io/#article-title).

**Comment by EdanToledo** [comment]
Hey! Just a heads up, my implementation of MAML was really off the cuff. I haven't thoroughly tested it in any capacity. It was just me trying to do basic MAML in my free time after work.

**Comment by alexunderch** [comment]
It means that it has an opportunity to be tested and inproved

**Comment by Howuhh** [comment]
@EdanToledo understandable! Unfortunately I have not found any other implementation on jax + ppo. Do you have any references you used when you were figuring it out?

**Comment by alexunderch** [comment]
I think if there are not many reliable implementations, it doesn't sound too hard to test on gymnax-like envs. I am interested in trying MAML for MARL experiments too.

**Comment by EdanToledo** [comment]
> @EdanToledo understandable! Unfortunately I have not found any other implementation on jax + ppo. Do you have any references you used when you were figuring it out (besides the original paper)?

I just used the paper tbh that's why it's super possible I messed up some aspects of it. I think there was some blog that implemented it in JAX but for supervised learning that I partially looked at but I don't remember it being that helpful.
