### ISSUE TITLE
observations of env when not RGB

### ISSUE THREAD

**Issue by wcarvalho** [corl-team/xland-minigrid#15]
Hello,

great codebase. I just want to double-check my understanding. for non-RGB experiments you've done, you use the uint8 grid values as inputs? I was expecting to see you convert them to 1-hots or something.

Thanks

**Comment by Howuhh** [comment]
Hi @wcarvalho! That's a good question! Converting them to embeddings or one-hot is the most correct way to work with this representation and I mention it in the paper. However, the baselines are currently use naive approach, which was taken from the [original baselines for minigrid](https://github.com/lcswillems/rl-starter-files), where the picture is fed to CNN as is.
